TEST_DURATION = 2  # seconds

MESSAGE_SMALL = b"Event Data"
MESSAGE_AVG = b"D" * (1024*20)  # 20k
MESSAGE_LARGE = b"E" * (1024*512)  # 512k

MESSAGE_SAMPLES = [
    MESSAGE_SMALL,
    #MESSAGE_AVG,
    #MESSAGE_LARGE,
]


